apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_HOST: 172.17.0.2
  POSTGRES_PORT: "5432"
  POSTGRES_DB: ***
  POSTGRES_USER: ***
  POSTGRES_PASSWORD: ***